ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PLAN_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PLAN_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PLAN_ARCHIVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PLAN_DELETED';

ALTER TABLE "Plan"
ALTER COLUMN "code" TYPE TEXT USING "code"::TEXT,
ADD COLUMN "version" INTEGER NOT NULL DEFAULT 0;

DROP TYPE "PlanCode";
